baseURL = 'https://opt-nc.github.io/odata-avps/'
locale = 'fr-fr'
defaultContentLanguage = 'fr'
title = "Emploi OPT-NC"
theme = 'hugo-theme-relearn'

[params]
  # Options du thème Relearn
  themeVariant = [ "opt-light", "opt-dark" ]
  landingPageName = "<i class='fa-fw fas fa-home'></i> Bienvenue"
  collapsibleMenu = true
  disableShortcutsTitle = true
  author = "OPT-NC"
  images = ["/assets/logo-opt.png"]

[params.topbar]
    sidebar = "show"

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-info-circle'></i> À propos"
pageRef = "/a-propos"
weight = 10

[outputFormats.jobs_sitemap]
  mediaType = "application/xml"
  baseName = "jobs-sitemap"
  isHTML = false

[outputFormats.flux_ats]
  mediaType = "application/xml"
  baseName = "flux_ats"
  isHTML = false

[outputs]
  home = ['html', 'rss', 'print','markdown','jobs_sitemap','flux_ats']
  page = ['html', 'print','markdown']
  section = ['html', 'rss', 'print','markdown']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # ✅ Autorise le HTML brut (comme ton footer <center>) dans le Markdown


[params.social]
  facebook  = "https://www.facebook.com/OPT.NC"
  twitter   = "https://twitter.com/opt_nc"
  instagram = "https://www.instagram.com/opt_nc/"
  youtube   = "https://www.youtube.com/user/optnc"
  linkedin  = "https://www.linkedin.com/company/opt-new-caledonia"
  tiktok    = "https://www.tiktok.com/discover/team-opt-nc"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  # OKF Bundle mounts
  [[module.mounts]]
    source = "content/commercial-et-clientele"
    target = "static/okf/commercial-et-clientele"
  [[module.mounts]]
    source = "content/ressources-humaines"
    target = "static/okf/ressources-humaines"
  [[module.mounts]]
    source = "content/poste-et-logistique"
    target = "static/okf/poste-et-logistique"
  [[module.mounts]]
    source = "content/telecommunications"
    target = "static/okf/telecommunications"
  [[module.mounts]]
    source = "content/informatique-et-technologies"
    target = "static/okf/informatique-et-technologies"
  [[module.mounts]]
    source = "content/administration-finance-et-juridique"
    target = "static/okf/administration-finance-et-juridique"