[project]
title = "Bourse de l'Emploi OPT"
description = "Espace de consultation des Avis de Vacances de Poste (AVP) pour les agents de l'OPT."
site_name = "AVPS OPT-NC"
site_description = "Avis de Vacances de Poste de l'Office des Postes et Télécommunications de Nouvelle-Calédonie"
site_author = "OPT-NC"
site_url = "https://opt-nc.github.io/odata-avps/"
repo_url = "https://github.com/opt-nc/odata-avps"
# On déclare le fichier CSS
extra_css = ["style/extra.css"]
extra_javascript = ["style/extra.js"]

docs_dir = "data"
# Dossier final généré (celui que GitHub Pages publiera)
site_dir = "public" 

[project.theme]
# On déclare le logo principal (qui s'affichera en haut à gauche par défaut)
logo = "assets/logo-opt.png"
favicon = "assets/logo-opt.png"
name = "material" 
palette = { primary = "blue", accent = "blue" } 
language = "fr"
custom_dir = "overrides"